# Dynamic Discord UM+ Configuration
# Configuration file for the Minecraft Server Status Bot
bot:
  token: "DISCORD_BOT_TOKEN"
  channel-id: "YOUR_CHANNEL_ID"

# Server configuration
server:
  name: "YOUR_SERVER_NAME"
  ip: "YOUR_SERVER_IP"
  port: 25565 #Default Bedrock port is 25565, change if needed
  type: "java" #Options: "java" or "bedrock"

# Optional: Customize the embed appearance
embed:
  online-color: "#00FF7F" #Spring Green
  offline-color: "#FF0000" #Red
  show-banner: false #Optional: Set to true to display a server banner in the embed
  banner-url: "YOUR_BANNER_URL" #Optional: URL to a server banner image
  show-title-image: false #Optional: Set to true to display a thumbnail/title image
  title-image-url: "YOUR_TITLE_IMAGE_URL" #Optional: URL to the thumbnail image
  footer:
    enabled: false
    text: "Your custom footer text!"

# Update interval in seconds (how often the bot checks the server status)
update-interval: 30

# Notification settings
notifications:
  online:
    enabled: false
    role-id: "ROLE_ID_TO_MENTION_ONLINE"
  offline:
    enabled: false
    role-id: "ROLE_ID_TO_MENTION_OFFLINE"
